# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/cart.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'protobuf/cart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protobuf/cart.proto\"U\n\x08\x43\x61rtItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01\"y\n\x03\x46\x65\x65\x12\r\n\x05total\x18\x01 \x01(\x01\x12\x14\n\x0cplatform_fee\x18\x02 \x01(\x01\x12\r\n\x05surge\x18\x03 \x01(\x01\x12\x10\n\x08\x64\x65livery\x18\x04 \x01(\x01\x12\x0b\n\x03tax\x18\x05 \x01(\x01\x12\x10\n\x08\x64iscount\x18\x06 \x01(\x01\x12\r\n\x05\x66inal\x18\x07 \x01(\x01\"\x8c\x01\n\x04\x43\x61rt\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x18\n\x05items\x18\x02 \x03(\x0b\x32\t.CartItem\x12\x11\n\x03\x66\x65\x65\x18\x03 \x01(\x0b\x32\x04.Fee\x12\x0e\n\x06\x63oupon\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.cart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARTITEM']._serialized_start=23
  _globals['_CARTITEM']._serialized_end=108
  _globals['_FEE']._serialized_start=110
  _globals['_FEE']._serialized_end=231
  _globals['_CART']._serialized_start=234
  _globals['_CART']._serialized_end=374
# @@protoc_insertion_point(module_scope)
