# .github/workflows/compose-integration.yml
name: Docker Compose Integration Test

on:
  pull_request:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Docker Compose
        run: docker compose -f Docker/docker-compose.yml up -d

      - name: Wait and Test API
        run: |
          sleep 15
          curl -f http://localhost:8000/health || exit 1
