# .github/workflows/python-lint-test.yml
name: Python Lint & Test

on:
  push:
    paths:
      - 'fastapi/**'
  pull_request:
    paths:
      - 'fastapi/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fastapi

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8 black pytest

      - name: Lint with flake8
        run: flake8 .

      - name: Format check with black
        run: black --check .

      - name: Run tests
        run: pytest
