name: Go Lint & Test

on:
  push:
    paths:
      - 'golang/**'
  pull_request:
    paths:
      - 'golang/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: golang

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./...

